# Generated by Django 3.2.7 on 2021-09-26 12:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicesApp', '0003_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Service Image'),
        ),
    ]
