# Generated by Django 3.2.7 on 2021-09-27 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicesApp', '0005_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
